### ISSUE TITLE
phi-toggle-sidebar doesn't work with empty ~/phi directory

### ISSUE THREAD

**Issue by DivineDominion** [brunocbr/phi-notes#2]
Wanted to try the most obvious thing: call the interactive functions and see what happens, starting with the sidebar.

`phi-toggle-sidebar` takes no arguments, and I ran it from `~/phi/test.txt`. 

Stack trace reveals the id parameter is nil, and that's not handled gracefully -- i.e. it crashes.

I wouldn't know what an expected value for that is. So could you maybe provide a quickstart README @brunocbr? I guess I can figure out the error handling once I know what the "happy path" is, too.

```
Debugger entered--Lisp error: (wrong-type-argument stringp nil)
  file-name-all-completions(nil "~/phi")
  (nth 0 (file-name-all-completions id phi-notes-path))
  phi-matching-file-name(nil)
  (find-file-noselect (phi-matching-file-name id))
  (phi-sidebar-adjust-buffer (find-file-noselect (phi-matching-file-name id)))
  (setq phi-sidebar-buffer (phi-sidebar-adjust-buffer (find-file-noselect (phi-matching-file-name id))))
  phi-sidebar-create-buffer(nil)
  (if phi-sidebar-buffer nil (phi-sidebar-create-buffer (phi-get-parent-note-id)))
  phi-toggle-sidebar()
  funcall-interactively(phi-toggle-sidebar)
  command-execute(phi-toggle-sidebar record)
  execute-extended-command(nil "phi-toggle-sidebar" nil)
  funcall-interactively(execute-extended-command nil "phi-toggle-sidebar" nil)
  command-execute(execute-extended-command nil nil :special)
  xah-fly-M-x()
  funcall-interactively(xah-fly-M-x)
  command-execute(xah-fly-M-x)
```

**Comment by brunocbr** [comment]
Christian, thank you for the observations. The functions will now raise an error when trying to visit a nonexistent parent note or when a matching file can't be found for a given note id.
